name: Test Jobs Exit plus file test

on:
  workflow_dispatch:
    inputs:
      filename:
        type: string
        description: Enter a sample filename with or without extension

jobs:
  echofile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: echofilename
        run: | 
          echo "string is ${{ github.event.inputs.filename }}"
          
  testfile:
    runs-on: ubuntu-latest
    needs: echofile
    steps:
      - name: testyes
        if: ${{ endsWith(github.event.inputs.filename, '.md') }}
        run: |
          echo "filename ${{github.event.inputs.filename}} ends with .md"
      - name: testno
        if: ${{ !endsWith(github.event.inputs.filename, '.md') }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('filename ${{github.event.inputs.filename}} does not end with .md')
          
  nextjobstep:
    runs-on: ubuntu-latest
    needs: testfile
    steps:
      - name: finaljob
        run: |
          echo "job completed successfully"
          
      
          
